/*
# ------------------------------------------------------------------------------
#
# Copyright (c) 1986-2019 Pixar. All rights reserved.
#
# The information in this file (the "Software") is provided for the exclusive
# use of the software licensees of Pixar ("Licensees").  Licensees have the
# right to incorporate the Software into other products for use by other
# authorized software licensees of Pixar, without fee. Except as expressly
# permitted herein, the Software may not be disclosed to third parties, copied
# or duplicated in any form, in whole or in part, without the prior written
# permission of Pixar.
#
# The copyright notices in the Software and this entire statement, including the
# above license grant, this restriction and the following disclaimer, must be
# included in all copies of the Software, in whole or in part, and all permitted
# derivative works of the Software, unless such copies or derivative works are
# solely in the form of machine-executable object code generated by a source
# language processor.
#
# PIXAR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING ALL
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL PIXAR BE
# LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION
# OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
# CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.  IN NO CASE WILL
# PIXAR'S TOTAL LIABILITY FOR ALL DAMAGES ARISING OUT OF OR IN CONNECTION WITH
# THE USE OR PERFORMANCE OF THIS SOFTWARE EXCEED $50.
#
# Pixar
# 1200 Park Ave
# Emeryville CA 94608
#
# ------------------------------------------------------------------------------
*/

#include "RixPattern.h"
#include "RixShadingUtils.h"

class AddNode : public RixPattern
{
public:

    AddNode();
    virtual ~AddNode();

    virtual int Init(RixContext &, RtUString const pluginpath) override;
    virtual RixSCParamInfo const *GetParamTable() override;
    virtual void Synchronize(
        RixContext&,
        RixSCSyncMsg,
        RixParameterList const*) override
    {
    }

    virtual void Finalize(RixContext &) override;

    virtual int ComputeOutputParams(RixShadingContext const *,
                                    RtInt *n, RixPattern::OutputSpec **outputs,
                                    RtPointer instanceData,
                                    RixSCParamInfo const *) override;

    virtual bool Bake2dOutput(
        RixBakeContext const*,
        Bake2dSpec&,
        RtPointer) override
    {
        return false;
    }

    virtual bool Bake3dOutput(
        RixBakeContext const*,
        Bake3dSpec&,
        RtPointer) override
    {
        return false;
    }

private:
    // Defaults
    RtFloat const m_float1;
    RtFloat const m_float2;
    RtInt const m_addMode;
    RtInt const m_clampMix;
    RtFloat const m_mix;
};

AddNode::AddNode() :
    m_float1(0.f),
    m_float2(0.f),
    m_addMode(0),
    m_clampMix(0),
    m_mix(0.f)
{
}

AddNode::~AddNode()
{
}

int
AddNode::Init(RixContext &ctx, RtUString const pluginpath)
{
    PIXAR_ARGUSED(ctx);
    PIXAR_ARGUSED(pluginpath);

    return 0;
}

enum paramId
{
    k_resultF=0,     // float output
    k_float1,
    k_float2,
    k_addMode,
    k_clampMix,
    k_mix,
    k_numParams
};

RixSCParamInfo const *
AddNode::GetParamTable()
{
    static RixSCParamInfo s_ptable[] =
    {
        // outputs
        RixSCParamInfo(RtUString("resultF"), k_RixSCFloat, k_RixSCOutput),

        // inputs
        RixSCParamInfo(RtUString("float1"), k_RixSCFloat),
        RixSCParamInfo(RtUString("float2"), k_RixSCFloat),
        RixSCParamInfo(RtUString("addMode"), k_RixSCInteger),
        RixSCParamInfo(RtUString("clampMix"), k_RixSCInteger),
        RixSCParamInfo(RtUString("mix"), k_RixSCFloat),

        RixSCParamInfo() // end of table
    };
    return &s_ptable[0];
}

void
AddNode::Finalize(RixContext &ctx)
{
    PIXAR_ARGUSED(ctx);
}

enum mixResult
{
    k_resultMixed,
    k_resultColor1,
    k_resultColor2
};

int
AddNode::ComputeOutputParams(RixShadingContext const *sctx,
                                RtInt *noutputs, OutputSpec **outputs,
                                RtPointer instanceData,
                                RixSCParamInfo const *ignored)
{
    PIXAR_ARGUSED(instanceData);
    PIXAR_ARGUSED(ignored);

    bool varying = true;
    RixSCType type;
    RixSCConnectionInfo cinfo;

    // Find the number of outputs
    RixSCParamInfo const* paramTable = GetParamTable();
    int numOutputs = -1;
    while (paramTable[++numOutputs].access == k_RixSCOutput) {}

    // Allocate and bind our outputs

   /* RixShadingContext::Allocator pool(sctx);
    OutputSpec *o = pool.AllocForPattern<OutputSpec>(3);
    *outputs = o;
    *noutputs = 1;


    RtFloat *resultF = NULL;
    resultF = pool.AllocForPattern<RtFloat>(sctx->numPts);
    o[0].paramId = k_resultF;
    o[0].detail  = k_RixSCVarying;
    o[0].value = (RtPointer) resultF;*/

    RixShadingContext::Allocator pool(sctx);
    OutputSpec* out = pool.AllocForPattern<OutputSpec>(numOutputs);
    *outputs = out;
    *noutputs = numOutputs;



    // looping through the different output ids
    for (int i = 0; i < numOutputs; ++i)
    {
        out[i].paramId = i;
        out[i].detail = k_RixSCInvalidDetail;
        out[i].value = NULL;

        type = paramTable[i].type;    // we know this
        sctx->GetParamInfo(i, &type, &cinfo);
        if(cinfo == k_RixSCNetworkValue)
        {
            if( type == k_RixSCColor )
            {
                out[i].detail = k_RixSCVarying;
                out[i].value = pool.AllocForPattern<RtColorRGB>(sctx->numPts);
            }
            else if( type == k_RixSCFloat )
            {
                out[i].detail = k_RixSCVarying;
                out[i].value = pool.AllocForPattern<RtFloat>(sctx->numPts);
            }
        }
    }

  /*  RtColorRGB* resultRGB = (RtColorRGB*) out[k_resultRGB].value;
    if(!resultRGB)
    {
        resultRGB = pool.AllocForPattern<RtColorRGB>(sctx->numPts);
    }
    RtFloat* resultR = (RtFloat*) out[k_resultR].value;
    RtFloat* resultG = (RtFloat*) out[k_resultG].value;
    RtFloat* resultB = (RtFloat*) out[k_resultB].value;
*/
    RtFloat* resultF = (RtFloat*) out[k_resultF].value;

    // read the inputs
    RtFloat const *mix;
    RtFloat const *float1;
    RtFloat const *float2;
    RtInt const *addMode;
    RtInt const *clampMix;

    int resultType = k_resultMixed;

        sctx->EvalParam(k_float1, -1, &float1, &m_float1, varying);
        sctx->EvalParam(k_float2, -1, &float2, &m_float2, varying);
        sctx->EvalParam(k_addMode, -1, &addMode, &m_addMode, varying);
        sctx->EvalParam(k_clampMix, -1, &clampMix, &m_clampMix, !varying);
        sctx->EvalParam(k_mix, -1, &mix, &m_mix, varying);
  for (int i = 0; i < sctx->numPts; ++i)
    {
        if( addMode[0] != 0){
            resultF[i] = RixMix(float1[i], float2[i],
                                clampMix[0]? RixClamp(mix[i], 0.f, 1.f): mix[i]);
        }else   {
            resultF[i] = float1[i] + float2[i];
            resultF[i] =  clampMix[0] ? RixClamp(mix[i], 0.f, 1.f) : resultF[i];
            }


        /*if(resultType == k_resultMixed)
        {
            resultRGB[i] = RixMix(color1[i], color2[i],
                                  clampMix[0]? RixClamp(mix[i], 0.f, 1.f): mix[i]);
        }
        else if(resultType == k_resultColor1)
        {
            resultRGB[i] = color1[i];
        }
        else // resultType == k_resultColor2
        {
            resultRGB[i] = color2[i];
        }

        if(resultR)
        {
            resultR[i] = resultRGB[i].r;
        }
        if(resultG)
        {
            resultG[i] = resultRGB[i].g;
        }
        if(resultB)
        {
            resultB[i] = resultRGB[i].b;
        }*/
    }

    return 0;
}

RIX_PATTERNCREATE
{
    PIXAR_ARGUSED(hint);

    return new AddNode();
}


RIX_PATTERNDESTROY
{
    delete ((AddNode*)pattern);
}
